name: "AWS ECS Task Deploy"
description: "Deploy production image to AWS ECS"
inputs:
  environment:
    description: Deployment environment
    required: true
  ecr_repository:
    description: ECR repository to pull image from
    required: true
  deployment_tag:
    description: Github Action deployment tag
    required: true
  run_preflight:
    description: Determines whether the preflight step should be triggered
    required: true
  desired_count:
    description: Number of tasks running in ECS service
    required: true
  allow_feature_branch_deployment:
    description: Allow deployment from feature branch
    required: true
  aws_access_key_id:
    description: AWS access key
    required: true
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_region:
    description: AWS region
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v5

    - id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Setup Python + Poetry
      uses: moneymeets/action-setup-python-poetry@master
      with:
        working_directory: ${{ github.action_path }}
        with_checks: 'false'
        # ToDo: Re-enable cache when https://github.com/actions/setup-python/issues/361 is fixed
        poetry_cache_enabled: 'false'

    - id: run-ecs-deploy
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        if [[ "${{ inputs.allow_feature_branch_deployment }}" == "true" ]]; then
          imageTag=$(echo ${{ github.ref_name }} | awk '{print tolower($0)}' | sed -e 's|/|-|g')
        else
          imageTag=master-${{ github.sha }}
        fi
        
        poetry run actions_helper ecs-deploy \
          --environment "${{ inputs.environment }}" \
          --allow-feature-branch-deployment "${{ inputs.allow_feature_branch_deployment }}" \
          --ecr-repository "${{ inputs.ecr_repository }}" \
          --deployment-tag "${{ inputs.deployment_tag }}" \
          --image-tag "$imageTag" \
          --run-preflight "${{ inputs.run_preflight }}" \
          --desired-count "${{ inputs.desired_count }}" \
          --aws-region "${{ inputs.aws_region }}"
